services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: webapi
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Search Path=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    profiles: ["api"]

  console:
    image: ${DOCKER_REGISTRY-}console
    container_name: console
    build:
      context: .
      dockerfile: src/Console/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ${CSV_FILE_PATH}:/app/data/input.csv
      - ./output:/app/output
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Search Path=postgres
      - CSV_FILE_PATH=/app/data/input.csv
    profiles: ["console"]

  database:
    image: postgres:alpine
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: '--locale-provider=icu --icu-locale=en-US --no-sync'
    restart: always
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    profiles: ["api", "console"]
